# please change this to your dataset root directory and data format
your_dataset_id:
    data_root: your_data_root
    data_format: parquet
    train_data: your_data_root/train.parquet
    valid_data: your_data_root/valid.parquet
    test_data: your_data_root/test.parquet
    